services:
  livebook:
    build:
      context: .
      dockerfile: docker/Dockerfile.parrot
    ports:
      - 8090:8090
      - 8091:8091
    environment:
      - LIVEBOOK_PORT=8090
      - LIVEBOOK_IFRAME_PORT=8091
